/* Stored procedures */
CONNECT C:\Office\Db\office.gdb;
OUTPUT "@2";

SELECT QTY||","||SSUM||","||TAXSUM FROM TILL WHERE TILLNUM = (SELECT MAX(TILLNUM) FROM TILLITEM WHERE BARCODE = (SELECT BARCODE FROM ITEM WHERE ITEMNAME = "@1"));

COMMIT;

EXIT;